name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run TESTS
        run: npm run test